# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
title = "dualie.ink"
greeting = "hi, i'm dualie"

[params]
# logo = "logo.png"
colorScheme = "slate"
footer.showThemeAttribution = false

[author]
name = "Lemniscate Duality Ink"
image = "picture.png"
headline = "i do stuff, sometimes"
# bio = "A little bit about me"
links = [
  { github = "https://github.com/3096" },
  { twitter = "https://twitter.com/dualie_ink" },
  { youtube = "https://www.youtube.com/dualie" },
  { discord = "https://discord.gg/BFEuuaBNR4" },
  { ko-fi = "https://ko-fi.com/the3096" },
  { envelope = "mailto:contact@dualie.ink" }
]

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
